B-4.1
Flartman/GetAPet pull request #5
Opened 2024-09-15 10:24 UTC by Flartman

2024-09-15 16:01 UTC, YaraOduvanchik requested changes

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.Domain/Volunteers/PaymentDetailsStorage.cs
> +        private readonly List<PaymentDetails> _paymantDetailsList = [];
Тут не нужен этот список, нужен только IReadOnlyList.

Нужно ещё добавить конструктор, в котором в поле PaymantDetailsList присваивается параметр типа IEnumerable<PaymentDetails>.

Ещё как вариант можно сделать ValueObjectList<T>, как Кирилл показывал на занятии 12

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.Domain/Volunteers/Pets/PetPhotoAlbum.cs
> +    {
Тут тоже самое, что я писал выше

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.Domain/Volunteers/SocialMediaStorage.cs
> +    {
Тут тоже самое, что я писал выше

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.API/appsettings.json
> +    "Database": "Server=localhost;Port=5434;Database=getapet;User Id=postgres;Password=postgres;"
Это должно быть в user secrets, а тут лучше указать например:
"Database": "Server=server;Port=port;Database=database;User Id=userid;Password=password;"

Это нужно чтобы данные о БД были видны только тебе

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.Infrastructure/ApplicationDbContext.cs
> +            optionsBuilder.UseSnakeCaseNamingConvention();
Тут можно ещё указать EnableSensitiveDataLogging

2024-09-15 16:01 UTC, n-cherashev commented on backend/src/GetAPet.Infrastructure/Configurations/VolunteerConfiguration.cs
> +            builder.HasMany(v => v.Pets);
Вот тут нужно вот так конфигурировать:

builder.HasMany(v => v.Pets)
            .WithOne()
            .HasForeignKey("volunteer_id");

2024-09-16 03:04 UTC, Flartman commented on backend/src/GetAPet.Domain/Volunteers/PaymentDetailsStorage.cs
> +        private readonly List<PaymentDetails> _paymantDetailsList = [];
Список поправил, но IEnumerable не использовал. В задании этого нет и в лекциях я еще этого не встречал, проведу рефакторинг когда встречу.

2024-09-16 04:41 UTC, YaraOduvanchik approved these changes

2024-09-16 12:50 UTC, merged